IP_MASTER1 = "192.168.101.10"
IP_WORKER1 = "192.168.101.11"

POD_NW_CIDR = "10.244.0.0/16"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "k3s-server" do |node|

    node.vm.provider "virtualbox" do |vb|
        vb.name = "k3s-server"
        vb.memory = 4096
        vb.cpus = 4

       vb.customize [
            "modifyvm", :id, "--uartmode1", "file",
            File.join(Dir.pwd, "tmp/k3s-server.log")
        ]
       vb.customize ["modifyvm", :id, "--nested-hw-virt", "on",]
    end

    node.vm.hostname = "k3s-server"
    node.vm.network :private_network, ip: IP_MASTER1
    node.disksize.size = '100GB'

    node.vm.provision "set-hosts", :type => "shell", :path => "scripts/set-hosts.sh" do |s|
      s.args = ["ensp0s8"]
    end

    
    node.vm.provision "update-dns", type: "shell", :path => "scripts/update-dns.sh"
    node.vm.provision "install-k3s", type: "shell", :path => "scripts/install-k3s.sh", env: {"MASTER_IP" => "#{IP_MASTER1}","WORKER_IP"=>"#{IP_WORKER1}"}
  end

    config.vm.define "k3s-agent1" do |node|

        node.vm.provider "virtualbox" do |vb|
            vb.name = "k3s-agent1"
            vb.memory = 4096
            vb.cpus = 2

            vb.customize [
                "modifyvm", :id, "--uartmode1", "file",
                File.join(Dir.pwd, "tmp/k3s-agent1.log")
            ]
            vb.customize ["modifyvm", :id, "--nested-hw-virt", "on",]
        end

        node.vm.hostname = "k3s-agent1"
        node.vm.network :private_network, ip: IP_WORKER1

        node.vm.provision "set-hosts", :type => "shell", :path => "scripts/set-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end

        node.vm.provision "update-dns", type: "shell", :path => "scripts/update-dns.sh"
        node.vm.provision "install-k3s", type: "shell", :path => "scripts/install-agents.sh",env: {"MASTER_IP" => "#{IP_MASTER1}","WORKER_IP"=>"#{IP_WORKER1}"}
        
    end
end
