IP_ELK1 = "192.168.101.20"
IP_ELK2 = "192.168.101.21"
IP_ELK3 = "192.168.101.22"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "ELK1" do |node|

    node.vm.provider "virtualbox" do |vb|
        vb.name = "ELK1"
        vb.memory = 3096
        vb.cpus = 4

       vb.customize [
            "modifyvm", :id, "--uartmode1", "file",
            File.join(Dir.pwd, "tmp/ELK1.log")
        ]
       vb.customize ["modifyvm", :id, "--nested-hw-virt", "on",]
    end

    node.vm.hostname = "ELK1"
    node.vm.network :private_network, ip: IP_ELK1
    node.disksize.size = '100GB'
    node.vm.provision "shell", inline: <<-SHELL 
    echo root:root | chpasswd
    sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sed -i -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    systemctl restart sshd
    SHELL
  end

    config.vm.define "ELK2" do |node|

        node.vm.provider "virtualbox" do |vb|
            vb.name = "ELK2"
            vb.memory = 3096
            vb.cpus = 2

            vb.customize [
                "modifyvm", :id, "--uartmode1", "file",
                File.join(Dir.pwd, "tmp/ELK2.log")
            ]
            vb.customize ["modifyvm", :id, "--nested-hw-virt", "on",]
        end

        node.vm.hostname = "ELK2"
        node.vm.network :private_network, ip: IP_ELK2
        node.vm.provision "shell", inline: <<-SHELL 
        echo root:root | chpasswd
        sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sed -i -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        systemctl restart sshd
        SHELL
        
    end

    config.vm.define "ELK3" do |node|

      node.vm.provider "virtualbox" do |vb|
          vb.name = "ELK3"
          vb.memory = 3096
          vb.cpus = 2

          vb.customize [
              "modifyvm", :id, "--uartmode1", "file",
              File.join(Dir.pwd, "tmp/ELK3.log")
          ]
          vb.customize ["modifyvm", :id, "--nested-hw-virt", "on",]
      end

      node.vm.hostname = "ELK3"
      node.vm.network :private_network, ip: IP_ELK3
      node.vm.provision "shell", inline: <<-SHELL 
      echo root:root | chpasswd
      sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sed -i -e 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
      systemctl restart sshd
      SHELL
      
  end
end
