IP_MASTER1 = "192.168.0.5"
IP_WORKER1 = "192.168.0.6"
IP_GW = "192.168.0.1"
NETWORK= "public_network"


Vagrant.configure("2") do |config|
    config.vm.box = "rockylinux/8"
    #config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
    end

  config.vm.define "k3s" do |node|

    node.vm.provider "virtualbox" do |vb|
        vb.name = "k3s"
        vb.memory = 4096
        vb.cpus = 4
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on",]
    end

    node.vm.hostname = "k3s"
    node.vm.network  NETWORK, ip: IP_MASTER1
    node.disksize.size = '100GB'

    node.vm.provision "set-hosts", :type => "shell", :path => "scripts/set-hosts.sh", env: {"MASTER_IP" => "#{IP_MASTER1}","WORKER_IP"=>"#{IP_WORKER1}"} do |s|
      s.args = ["eth1"]
    end

    node.vm.provision "shell", run: "always", inline: "ip route del default && ip route add default via #{IP_GW} dev eth1"
    node.vm.provision "update-dns", type: "shell", :path => "scripts/update-dns.sh"
    node.vm.provision "install-k3s", type: "shell", :path => "scripts/install-k3s.sh", env: {"MASTER_IP" => "#{IP_MASTER1}","WORKER_IP"=>"#{IP_WORKER1}"}
    node.vm.provision "agents-env-file", type: "shell", :path => "scripts/configure-agets-env.sh", env: {"MASTER_IP" => "#{IP_MASTER1}","WORKER_IP"=>"#{IP_WORKER1}"}
  end

    config.vm.define "k3s-worker1" do |node|

        node.vm.provider "virtualbox" do |vb|
            vb.name = "k3s-worker1"
            vb.memory = 4096
            vb.cpus = 2

            vb.customize [
                "modifyvm", :id, "--uartmode1", "file",
                File.join(Dir.pwd, "tmp/k3s-worker1.log")
            ]
            vb.customize ["modifyvm", :id, "--nested-hw-virt", "on",]
        end

        node.vm.hostname = "k3s-worker1"
        node.vm.network NETWORK, ip: IP_WORKER1

        node.vm.provision "set-hosts", :type => "shell", :path => "scripts/set-hosts.sh",env: {"MASTER_IP" => "#{IP_MASTER1}","WORKER_IP"=>"#{IP_WORKER1}"} do |s|
          s.args = ["eth1"]
        end

        node.vm.provision "shell", run: "always", inline: "ip route del default && ip route add default via #{IP_GW} dev eth1"
        node.vm.provision "update-dns", type: "shell", :path => "scripts/update-dns.sh"
        node.vm.provision "install-k3s", type: "shell", :path => "scripts/install-agents.sh",env: {"MASTER_IP" => "#{IP_MASTER1}","WORKER_IP"=>"#{IP_WORKER1}"}
        
    end
end
